### ISSUE TITLE
学习

### ISSUE THREAD

**Issue by songjian0270** [godcong/chronos#1]
termInfoList 这个里面的值是做什么的呢，如何定义的呢大佬

**Comment by godcong** [comment]
这是已经理好的每年的数据

**Comment by songjian0270** [comment]
如果要自定义如何定义的呢

**Comment by godcong** [comment]
自己定义的话得用另一套算法,但是这个算法有点误差. 算八字那个就是用的算法.
这个是现成的,是列表法,不是计算法.

**Comment by songjian0270** [comment]
列表法的规则有吗

**Comment by songjian0270** [comment]
func GetTermInfo(y, n int) int {
	y = fixSuffix(y)
	if y < 0 || y > len(termInfoList) {
		return -1
	}
	if n < 1 || n > 24 {
		return -1
	}
	i := (n - 1) / 4 * 5
	n = (n - 1) % 4
	idx, _ := strconv.ParseInt(termInfoList[y][i:i+5], 16, 64)
	a := strconv.FormatInt(idx, 10)
	day := []string{a[0:1], a[1:3], a[3:4], a[4:6]}
	i, _ = strconv.Atoi(day[n])
	return i
}

不是很理解取值之后，得到个整型，然后截取放到数组

**Comment by songjian0270** [comment]
func StemBranchMonth(y, m, d int) string {
	//月柱 1900年1月小寒以前为 丙子月(60进制12)
	fir := GetTermInfo(y, m*2-1) //返回当月「节」为几日开始

	//依据12节气修正干支月
	var sb = GetStemBranch(fixSuffix(y)*12 + m + 11)
	if d >= fir {
		sb = GetStemBranch(fixSuffix(y)*12 + m + 12)
	}
	return sb
}

输入天数和GetTermInfo 比 这个算法怎么理解大佬

**Comment by godcong** [comment]
你看调用的地方,一个月里面有2个节气,所以返回的是第几天,就一个整数

**Comment by songjian0270** [comment]
GetTermInfo 得到个整型，16进制然后截取 在放在数组中 这个规则是什么的呢

**Comment by godcong** [comment]
没有什么规则啊,这就是一个列表,哪一位对应哪一个节气,这个节气是第几天.

**Comment by songjian0270** [comment]
嗯嗯
