### ISSUE TITLE
大佬在学习go请教下ParseInLocation 这个是什么意思的呢

### ISSUE THREAD

**Issue by songjian0270** [godcong/chronos#3]
func lunarStart() time.Time {
	loc, _ := time.LoadLocation("Local")
	start, err := time.ParseInLocation("2006/01/02", "1900/01/30", loc)
	if err != nil {
		fmt.Println(err.Error())
	}
	return start
}

大佬，这个ParseInLocation 意思是在2006-1900之间转换吗？

**Comment by godcong** [comment]
这个是时区啊，第一个个格式，第二个是要转换的日期，第三个是时区。Local代表本地时区
也可以是Asia/Shanghai这些
你可以看到golang `time`库的说明

**Comment by songjian0270** [comment]
第一个参数格式确定值是随意写的吗

**Comment by godcong** [comment]
> 第一个参数格式确定值是随意写的吗

第一个是格式，有严格要求的。就和其他语言的yy:MM:dd一样

**Comment by songjian0270** [comment]
看了半天格式的go为什么不直接yy:MM:dd多好  ，谢谢的呢
